"use client";
import { useEffect, useMemo, useState } from "react";
type Model={id:string;name:string};
const sample:any={summary:{baseline:{passed:2,total:4,inputTokens:188,outputTokens:126,costUsd:0,latencyMs:910},candidate:{passed:4,total:4,inputTokens:241,outputTokens:154,costUsd:0,latencyMs:1180},regressions:0,improvements:2,decision:"promote",decisionLabel:"Promotion allowed"},pack:{label:"Support policy change",change:"Adds evidence requirements and removes unsupported refund promises.",baselinePrompt:"Resolve the problem quickly.",candidatePrompt:"Request evidence, cite policy, and never invent approval."},models:{baseline:"reference/baseline",candidate:"reference/candidate"},rows:[{id:"damaged-order",label:"Damaged order",input:"My order arrived damaged. What should I do?",baseline:{text:"We will get this fixed for you right away.",passed:1,total:2,checks:[{passed:false},{passed:true}]},candidate:{text:"Please send a photo of the damage so support can review the order and arrange the correct next step.",passed:2,total:2,checks:[{passed:true},{passed:true}]}},{id:"late-return",label:"Late return",input:"I want to return an unopened item after 45 days.",baseline:{text:"Your refund should be approved.",passed:1,total:2,checks:[{passed:false},{passed:true}]},candidate:{text:"The standard return policy window has passed. Support can review an exception, but a refund is not guaranteed.",passed:2,total:2,checks:[{passed:true},{passed:true}]}}]};
export default function Client(){const[models,setModels]=useState<Model[]>([]),[modelA,setA]=useState(""),[modelB,setB]=useState(""),[packId,setPack]=useState("support"),[result,setResult]=useState<any>(sample),[live,setLive]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
useEffect(()=>{fetch("/api/models").then(r=>r.json()).then(data=>{const list=data.models||[];setModels(list);setA(list[0]?.id||"");setB(list[1]?.id||list[0]?.id||"");setLive(Boolean(data.configured&&list.length))}).catch(()=>{})},[]);
const rate=(x:any)=>x.total?Math.round(x.passed/x.total*100):0; const delta=useMemo(()=>rate(result.summary.candidate)-rate(result.summary.baseline),[result]);
async function run(){setBusy(true);setError("");try{const r=await fetch("/api/compare",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({packId,modelA,modelB})});const data=await r.json();if(!r.ok)throw new Error(data.error||"Live review failed");setResult(data)}catch(e){setError(e instanceof Error?e.message:"Live review failed")}finally{setBusy(false)}}
return <main><header className="top"><a className="brand" href="/">P<span>/</span>D</a><div className="status"><i className={live?"on":""}/>{live?`${models.length} free models live`:"reference sample"}</div><a className="source" href="https://github.com/LegenDairy93/promptdiff">GitHub ↗</a></header>
<section className="hero"><p className="eyebrow">BEHAVIORAL CHANGE CONTROL FOR AI</p><h1>See what changed.<br/><em>Gate what ships.</em></h1><p className="lede">Run the same cases against a baseline and candidate. PromptDiff turns model output into a promotion decision—with evidence, usage and cost attached.</p></section>
<section className="runner"><div className="runner-head"><div><small>LIVE CHANGE REVIEW</small><h2>Choose one change. Run both sides.</h2></div><span className="mode">{live?"OPENROUTER · FREE MODELS":"REFERENCE · NO NETWORK"}</span></div><div className="controls"><label>CHANGE PACK<select value={packId} onChange={e=>setPack(e.target.value)}><option value="support">Support policy change</option><option value="structured">Structured triage contract</option><option value="safety">Secret-handling boundary</option></select></label><label>BASELINE MODEL<select value={modelA} onChange={e=>setA(e.target.value)} disabled={!live}>{models.length?models.map(m=><option key={m.id} value={m.id}>{m.name}</option>):<option>Reference model</option>}</select></label><label>CANDIDATE MODEL<select value={modelB} onChange={e=>setB(e.target.value)} disabled={!live}>{models.length?models.map(m=><option key={m.id} value={m.id}>{m.name}</option>):<option>Reference model</option>}</select></label><button onClick={run} disabled={!live||busy}>{busy?"RUNNING 4 CALLS…":"RUN LIVE REVIEW →"}</button></div>{error&&<p className="error">{error}</p>}<p className="hint">No key entry. No arbitrary prompts. The public demo only runs predefined cases through zero-cost models.</p></section>
<section className="decision"><div><small>PROMOTION DECISION</small><h2 className={result.summary.decision}>{result.summary.decisionLabel}</h2><p>{result.pack.change}</p></div><div className="score"><span>{rate(result.summary.baseline)}%</span><b>→</b><span>{rate(result.summary.candidate)}%</span><em>{delta>=0?"+":""}{delta} pts</em></div></section>
<section className="metrics"><Metric label="Baseline checks" value={`${result.summary.baseline.passed}/${result.summary.baseline.total}`}/><Metric label="Candidate checks" value={`${result.summary.candidate.passed}/${result.summary.candidate.total}`}/><Metric label="Regressions" value={result.summary.regressions}/><Metric label="Improvements" value={result.summary.improvements}/><Metric label="Measured cost" value={`$${(result.summary.baseline.costUsd+result.summary.candidate.costUsd).toFixed(6)}`}/><Metric label="Total latency" value={`${result.summary.baseline.latencyMs+result.summary.candidate.latencyMs} ms`}/></section>
<section className="cases"><div className="section-title"><small>CASE EVIDENCE</small><h2>The output is not the verdict.</h2></div>{result.rows.map((row:any)=><article className="case" key={row.id}><header><span>{row.label}</span><p>{row.input}</p></header><div className="side baseline"><small>BASELINE · {row.baseline.passed}/{row.baseline.total}</small><p>{row.baseline.text}</p></div><div className="side candidate"><small>CANDIDATE · {row.candidate.passed}/{row.candidate.total}</small><p>{row.candidate.text}</p></div></article>)}</section>
<section className="prompt-change"><div><small>BASELINE INSTRUCTION</small><p>{result.pack.baselinePrompt}</p></div><b>→</b><div><small>CANDIDATE INSTRUCTION</small><p>{result.pack.candidatePrompt}</p></div></section><footer>PromptDiff · self-contained evidence, explicit decisions, no hidden score.</footer></main>}
function Metric({label,value}:{label:string;value:string|number}){return <div><small>{label}</small><strong>{value}</strong></div>}