import { getPack } from "../../../lib/packs";
import { complete, configured } from "../../../lib/openrouter";
function check(text:string,spec:any){const lower=text.toLowerCase(); if(spec.type==="contains")return lower.includes(String(spec.value).toLowerCase()); if(spec.type==="not_contains")return !lower.includes(String(spec.value).toLowerCase()); if(spec.type==="max_length")return text.length<=spec.limit; if(spec.type==="json_keys"){try{const value=JSON.parse(text.replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/, "")); return spec.keys.every((key:string)=>Object.hasOwn(value,key))}catch{return false}} return false}
export async function POST(request:Request){
  if(!configured())return Response.json({error:"Live models are not configured."},{status:503});
  try{const body:any=await request.json(); const pack=getPack(String(body.packId||"")); const modelA=String(body.modelA||""); const modelB=String(body.modelB||""); if(!modelA||!modelB)throw new Error("Choose both models.");
    const rows=[]; for(const testCase of pack.cases){const [a,b]=await Promise.all([complete(modelA,pack.baselinePrompt,testCase.input),complete(modelB,pack.candidatePrompt,testCase.input)]); const checksA=testCase.checks.map(spec=>({label:spec.type,passed:check(a.text,spec)})); const checksB=testCase.checks.map(spec=>({label:spec.type,passed:check(b.text,spec)})); rows.push({id:testCase.id,label:testCase.label,input:testCase.input,baseline:{...a,checks:checksA,passed:checksA.filter(x=>x.passed).length,total:checksA.length},candidate:{...b,checks:checksB,passed:checksB.filter(x=>x.passed).length,total:checksB.length}})}
    const totals=(side:"baseline"|"candidate")=>rows.reduce((acc:any,row:any)=>{const item=row[side]; acc.passed+=item.passed; acc.total+=item.total; acc.inputTokens+=(item.usage.inputTokens||0); acc.outputTokens+=(item.usage.outputTokens||0); acc.costUsd+=(item.usage.costUsd||0); acc.latencyMs+=item.latencyMs; return acc},{passed:0,total:0,inputTokens:0,outputTokens:0,costUsd:0,latencyMs:0}); const baseline=totals("baseline"),candidate=totals("candidate"); const regressions=rows.reduce((sum,row)=>sum+row.baseline.checks.filter((x:any,i:number)=>x.passed&&!row.candidate.checks[i].passed).length,0); const improvements=rows.reduce((sum,row)=>sum+row.candidate.checks.filter((x:any,i:number)=>x.passed&&!row.baseline.checks[i].passed).length,0); const blocked=regressions>0||candidate.passed<candidate.total;
    return Response.json({schemaVersion:"promptdiff.web-comparison.v1",generatedAt:new Date().toISOString(),pack:{id:pack.id,label:pack.label,change:pack.change,baselinePrompt:pack.baselinePrompt,candidatePrompt:pack.candidatePrompt},models:{baseline:modelA,candidate:modelB},summary:{baseline,candidate,regressions,improvements,decision:blocked?"block":"promote",decisionLabel:blocked?"Block promotion":"Promotion allowed"},rows});
  }catch(error){return Response.json({error:(error instanceof Error?error.message:"Comparison failed").replace(/sk-or-[A-Za-z0-9_-]+/g,"[REDACTED]").slice(0,500)},{status:400})}
}